#!/bin/bash
echo "Enter the first number"
read variables
fact=1
for i in $variables
do
num=$i
fact=1
while [ $num -gt 0 ]
do
fact=`expr $num \* $fact`
num=`expr $num - 1`
done
echo "The factorial of $i is $fact"
done
